build:
    - exec: "python"
      beforeFiles: "CocoIDE-V1.91/cdm8_asm_build.py"
      afterFiles: "-o CocoIDE-V1.91/debug.cdm8dbg.yaml"
      changeExt: "asm"
run:
  - exec: "python"
    beforeFiles: "CocoIDE-V1.91/cdm8_emu_main.py"
    afterFiles: ""
    changeExt: "img"
debug:
  - exec: "python"
    beforeFiles: "CocoIDE-V1.91/cdm8_emu_debug.py"
    afterFiles: ""
    changeExt: "img"